CREATE TABLE "线路主表" (
"线路id" INT NOT NULL,
"线路类型" CHARACTER(2) NOT NULL 'DX',
"旅游类型" CHARACTER(3) NOT NULL,
"系统编号" CHARACTER(30) NOT NULL,
"自定义编号" CHARACTER(30) NULL,
"线路起点" INT NOT NULL,
"线路终点" INT NOT NULL,
"主标题" CHARACTER(200) NOT NULL,
"副标题" CHARACTER(60) NULL,
"描述" CHARACTER(500) NULL,
"线路主题id" CHARACTER(50) NULL,
"关键字" INT NOT NULL,
"天数" INT NOT NULL,
"住宿天数" INT NOT NULL,
"住宿类型" INT NULL,
"住宿名称" CHARACTER(200) NULL,
"应急电话" CHARACTER(20) NOT NULL,
"报名截止时间" CHARACTER(8) NOT NULL,
"周末计算在内" CHARACTER(1) NOT NULL 'N',
"是否支持选座" CHARACTER(1) NOT NULL 'Y',
"最小成团人数" INT NOT NULL,
"下单是否需确认" CHARACTER NOT NULL 'N',
"状态" CHARACTER(2) NOT NULL 'T',
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP ,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP ,
PRIMARY KEY ("线路id") 
);

CREATE TABLE "站点管理" (
"站点id" INT NOT NULL,
"站点名称" CHARACTER(100) NOT NULL,
"站点类型" CHARACTER(100) NOT NULL,
"创建人" CHARACTER(200) NULL,
"创建时间" DATE NULL CURRENT_TIMESTAMP ,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP ,
PRIMARY KEY ("站点id") 
);

CREATE TABLE "目的地" (
"目的地id" INT NOT NULL,
PRIMARY KEY ("目的地id") 
);

CREATE TABLE "旅游类型" (
"类型id" INT NOT NULL,
"类型名称" CHARACTER(200) NOT NULL,
PRIMARY KEY ("类型id") 
);

CREATE TABLE "线路主题" (
"主题id" INT NOT NULL,
"主题名称" CHARACTER(200) NOT NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NOT NULL 'anonymous',
"最后修改时间" DATE NOT NULL CURRENT_TIMESTAMP ,
PRIMARY KEY ("主题id") 
);

CREATE TABLE "线路关键字" (
"关键字id" INT NOT NULL,
"关键字" CHARACTER(200) NOT NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP ,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP ,
PRIMARY KEY ("关键字id") 
);

CREATE TABLE "住宿类型" (
"住宿id" INT NOT NULL,
"住宿类型" CHARACTER NOT NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP ,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP ,
PRIMARY KEY ("住宿id") 
);

CREATE TABLE "接送信息" (
"接送信息id" INT NOT NULL,
"线路主表id" INT NOT NULL,
"始发站" INT NOT NULL,
"发车时间" CHARACTER(5) NOT NULL,
"去程是否接送" CHARACTER(1) NOT NULL 'N',
"回程是否接送" CHARACTER(1) NOT NULL 'N',
"创建人" CHARACTER VARYING(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER VARYING(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("接送信息id") 
);

CREATE TABLE "接送规则" (
"接送规则id" INT NOT NULL,
"接送标识" CHARACTER(2) NOT NULL,
"上车点" CHARACTER(200) NOT NULL,
"时间" CHARACTER(5) NOT NULL,
"价格" NUMERIC(20,3) NOT NULL,
"备注" CHARACTER(200) NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER VARYING(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("接送规则id") 
);

CREATE TABLE "线路扩展信息" (
"扩展信息id" INT NOT NULL,
"线路主键id" INT NOT NULL,
"特别提醒" CHARACTER(500) NOT NULL,
"线路特色" CHARACTER(500) NULL,
"费用包含" CHARACTER(500) NOT NULL,
"费用不包含" CHARACTER(500) NOT NULL,
"补充说明" CHARACTER(500) NULL,
"购物说明" CHARACTER(500) NULL,
"注意事项" CHARACTER(500) NOT NULL,
"创建人" CHARACTER VARYING(255) NOT NULL,
"创建时间" CHARACTER VARYING(255) NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER VARYING(255) NULL 'anonymous',
"最后修改时间" CHARACTER VARYING(255) NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("扩展信息id") 
);

CREATE TABLE "团体管理" (
"团体id" INT NOT NULL,
"团体编号" CHARACTER(20) NOT NULL,
"路线id" INT NOT NULL,
"团体名称" CHARACTER(200) NOT NULL,
"出团开始时间" DATE NOT NULL,
"出团结束时间" DATE NOT NULL,
"状态" CHARACTER(1) NOT NULL 'T',
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("团体id") 
);

CREATE TABLE "游客信息表" (
"游客信息id" INT NOT NULL,
"团体id" INT NOT NULL,
"旅游车次" INT NULL,
"游客姓名" CHARACTER(200) NOT NULL,
"成人/儿童" CHARACTER(1) NOT NULL 'M',
"游客证件" CHARACTER(18) NULL,
"游客座位" CHARACTER(10) NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("游客信息id") 
);

CREATE TABLE "会员表" (
"会员id" INTEGER NOT NULL,
"会员类型" CHARACTER(1) NOT NULL 'U',
"会员姓名" CHARACTER(200) NOT NULL,
"电话" CHARACTER(20) NOT NULL,
"会员证件" CHARACTER(18) NOT NULL,
"会员状态" CHARACTER(1) NOT NULL 'N',
"创建人" CHARACTER(200) NULL,
"创建时间" DATE NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("会员id") 
);

CREATE TABLE "车次配置表" (
"车次id" INT NOT NULL,
"车次编号" CHARACTER(20) NOT NULL,
"车次名称" CHARACTER(20) NOT NULL,
"车牌号" CHARACTER(10) NOT NULL,
"创建人" CHARACTER(200) NULL,
"创建时间" DATE NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("车次id") 
);

CREATE TABLE "操作员表" (
"操作员id" INT NOT NULL,
"会员id" INT NOT NULL,
"操作员登录账户" CHARACTER(100) NOT NULL,
"操作员密码" CHARACTER(100) NOT NULL,
"操作员姓名" CHARACTER(200) NOT NULL,
"操纵员性别" CHARACTER(1) NULL,
"口令重置时间" DATE NOT NULL CURRENT_TIMESTAMP,
"登录错误次数" INT NOT NULL 0,
"操作员状态" CHARACTER(1) NOT NULL 'R',
"最后登录时间" DATE NULL CURRENT_TIMESTAMP,
"最后登录ip" CHARACTER(15) NOT NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("操作员id") 
);

CREATE TABLE "订单表" (
"订单id" INT NOT NULL,
"订单编号" CHARACTER(20) NOT NULL,
"线路id" INT NOT NULL,
"分销商id" INT NOT NULL,
"订单金额" NUMERIC(24,3) NULL,
"出发日期" DATE NULL,
"订单状态" CHARACTER(1) NULL 'D',
"订单生成时间" DATE NULL CURRENT_TIMESTAMP,
"创建人" CHARACTER(200) NULL,
"创建时间" DATE NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("订单id") 
);

CREATE TABLE "付款表" (
"付款id" INT NOT NULL,
"付款编号" CHARACTER(20) NOT NULL,
"自定义编号" CHARACTER(20) NULL,
"订单id" INT NOT NULL,
"订单应付金额" NUMERIC(24,3) NOT NULL,
"订单实付金额" NUMERIC(24,3) NULL,
"预付款金额" NUMERIC(24,3) NULL,
"订单实收金额" NUMERIC(24,3) NULL,
"预付款时间" DATE NULL,
"尾款" NUMERIC(24,3) NULL,
"订单应收金额" NUMERIC(24,3) NOT NULL,
"尾款支付时间" DATE NULL,
"付款人" CHARACTER(200) NOT NULL,
"付款时间" DATE NOT NULL CURRENT_TIMESTAMP,
"付款状态" CHARACTER(1) NOT NULL 'D',
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("付款id") 
);

CREATE TABLE "日志表" (
"日志id" INT NOT NULL,
"操作内容" CHARACTER(500) NOT NULL,
"操作人" CHARACTER(200) NOT NULL,
"操作时间" DATE NOT NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("日志id") 
);

CREATE TABLE "角色表" (
"角色id" INT NOT NULL,
"角色名称" CHARACTER(200) NOT NULL,
"备注" CHARACTER(500) NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("角色id") 
);

CREATE TABLE "权限表" (
"权限id" INT NOT NULL,
"权限名称" CHARACTER(200) NOT NULL,
"操作名称" CHARACTER(200) NOT NULL,
"备注" CHARACTER(500) NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
"最后修改人" CHARACTER(200) NULL 'anonymous',
"最后修改时间" DATE NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("权限id") 
);

CREATE TABLE "角色权限表" (
"角色权限id" INT NOT NULL,
"角色id" INT NOT NULL,
"权限id" INT NOT NULL,
"创建人" CHARACTER(200) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("角色权限id") 
);

CREATE TABLE "消息通知表" (
"消息通知id" INT NOT NULL,
"消息类型" CHARACTER(3) NOT NULL 'ORD',
"是否已读" CHARACTER(1) NOT NULL 'N',
"消息内容" CHARACTER(500) NOT NULL,
"创建时间" DATE NOT NULL CURRENT_TIMESTAMP,
PRIMARY KEY ("消息通知id") 
);

