package com.lhzl.drp.dao;

import com.lhzl.drp.model.BookCode;

import java.util.List;
import java.util.Map;

public interface BookCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int deleteByPrimaryKey(Long codeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int insert(BookCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int insertSelective(BookCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    BookCode selectByPrimaryKey(Long codeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int updateByPrimaryKeySelective(BookCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int updateByPrimaryKey(BookCode record);

    /**
     * 查询字典代码.
     * @param map
     * @return
     */
    List<BookCode> queryBookCode(Map<String, Object> map);
}