package com.lhzl.drp.dao;

import com.lhzl.drp.model.BookCode;

public interface BookCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int deleteByPrimaryKey(Long codeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int insert(BookCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int insertSelective(BookCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    BookCode selectByPrimaryKey(Long codeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int updateByPrimaryKeySelective(BookCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book_code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    int updateByPrimaryKey(BookCode record);
}