package com.lhzl.drp.dao;

import com.lhzl.drp.model.Groupinfo;

public interface GroupinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_groupinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int deleteByPrimaryKey(Long groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_groupinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int insert(Groupinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_groupinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int insertSelective(Groupinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_groupinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    Groupinfo selectByPrimaryKey(Long groupid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_groupinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKeySelective(Groupinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_groupinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKey(Groupinfo record);
}