package com.lhzl.drp.dao;

import com.lhzl.drp.model.Keywords;

public interface KeywordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_keywords
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int deleteByPrimaryKey(Long keyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_keywords
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int insert(Keywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_keywords
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int insertSelective(Keywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_keywords
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    Keywords selectByPrimaryKey(Long keyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_keywords
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int updateByPrimaryKeySelective(Keywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_keywords
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int updateByPrimaryKey(Keywords record);
}