package com.lhzl.drp.dao;

import com.lhzl.drp.model.Lineinfo;

public interface LineinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lineinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long lineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lineinfo
     *
     * @mbggenerated
     */
    int insert(Lineinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lineinfo
     *
     * @mbggenerated
     */
    int insertSelective(Lineinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lineinfo
     *
     * @mbggenerated
     */
    Lineinfo selectByPrimaryKey(Long lineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lineinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Lineinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lineinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Lineinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_lineinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Lineinfo record);
}