package com.lhzl.drp.dao;

import com.lhzl.drp.model.Loginfo;

public interface LoginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_loginfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int deleteByPrimaryKey(Long logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_loginfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int insert(Loginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_loginfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int insertSelective(Loginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_loginfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    Loginfo selectByPrimaryKey(Long logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_loginfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKeySelective(Loginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_loginfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Loginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_loginfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKey(Loginfo record);
}