package com.lhzl.drp.dao;

import com.lhzl.drp.model.Messageinfo;

public interface MessageinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_messageinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int deleteByPrimaryKey(Long msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_messageinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int insert(Messageinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_messageinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int insertSelective(Messageinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_messageinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    Messageinfo selectByPrimaryKey(Long msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_messageinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKeySelective(Messageinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_messageinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Messageinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_messageinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKey(Messageinfo record);
}