package com.lhzl.drp.dao;

import com.lhzl.drp.model.Operatorinfo;

public interface OperatorinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int deleteByPrimaryKey(Long operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int insert(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int insertSelective(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    Operatorinfo selectByPrimaryKey(Long operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int updateByPrimaryKeySelective(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    int updateByPrimaryKey(Operatorinfo record);
}