package com.lhzl.drp.dao;

import com.lhzl.drp.model.Operatorinfo;

public interface OperatorinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated
     */
    int insert(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated
     */
    int insertSelective(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated
     */
    Operatorinfo selectByPrimaryKey(Long operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Operatorinfo record);
}