package com.lhzl.drp.dao;

import com.lhzl.drp.model.Operatorinfo;
import com.lhzl.drp.model.Userinfo;

import java.util.List;
import java.util.Map;

public interface OperatorinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int deleteByPrimaryKey(Long operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int insert(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int insertSelective(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    Operatorinfo selectByPrimaryKey(Long operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int updateByPrimaryKeySelective(Operatorinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_operatorinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int updateByPrimaryKey(Operatorinfo record);

    /**
     * 查询操作员
     *
     * @param map
     * @return
     */
    List<Operatorinfo> queryOper(Map<String, Object> map);
}