package com.lhzl.drp.dao;

import com.lhzl.drp.model.Orderinfo;

public interface OrderinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orderinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orderinfo
     *
     * @mbggenerated
     */
    int insert(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orderinfo
     *
     * @mbggenerated
     */
    int insertSelective(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orderinfo
     *
     * @mbggenerated
     */
    Orderinfo selectByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orderinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Orderinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_orderinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Orderinfo record);
}