package com.lhzl.drp.dao;

import com.lhzl.drp.model.Payinfo;

public interface PayinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_payinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long payid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_payinfo
     *
     * @mbggenerated
     */
    int insert(Payinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_payinfo
     *
     * @mbggenerated
     */
    int insertSelective(Payinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_payinfo
     *
     * @mbggenerated
     */
    Payinfo selectByPrimaryKey(Long payid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_payinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Payinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_payinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Payinfo record);
}