package com.lhzl.drp.dao;

import com.lhzl.drp.model.Rolepermissioninfo;

public interface RolepermissioninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rolepermissioninfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int deleteByPrimaryKey(Long rlpmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rolepermissioninfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int insert(Rolepermissioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rolepermissioninfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int insertSelective(Rolepermissioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rolepermissioninfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    Rolepermissioninfo selectByPrimaryKey(Long rlpmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rolepermissioninfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int updateByPrimaryKeySelective(Rolepermissioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_rolepermissioninfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int updateByPrimaryKey(Rolepermissioninfo record);
}