package com.lhzl.drp.dao;

import com.lhzl.drp.model.Stationinfo;

public interface StationinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stationinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int deleteByPrimaryKey(Long stationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stationinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int insert(Stationinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stationinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int insertSelective(Stationinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stationinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    Stationinfo selectByPrimaryKey(Long stationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stationinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKeySelective(Stationinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_stationinfo
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    int updateByPrimaryKey(Stationinfo record);
}