package com.lhzl.drp.dao;

import com.lhzl.drp.model.Themeinfo;

public interface ThemeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_themeinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int deleteByPrimaryKey(Long themeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_themeinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int insert(Themeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_themeinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int insertSelective(Themeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_themeinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    Themeinfo selectByPrimaryKey(Long themeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_themeinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int updateByPrimaryKeySelective(Themeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_themeinfo
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    int updateByPrimaryKey(Themeinfo record);
}