package com.lhzl.drp.dao;

import com.lhzl.drp.model.Traininfo;

public interface TraininfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traininfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long trainid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traininfo
     *
     * @mbggenerated
     */
    int insert(Traininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traininfo
     *
     * @mbggenerated
     */
    int insertSelective(Traininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traininfo
     *
     * @mbggenerated
     */
    Traininfo selectByPrimaryKey(Long trainid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Traininfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_traininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Traininfo record);
}