package com.lhzl.drp.model;

import java.util.Date;

public class BookCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_code.codeId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private Long codeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_code.code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_code.description
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_code.creatby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private String creatby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_code.creatTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_code.updateby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_code.updateTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_code.codeId
     *
     * @return the value of tbl_book_code.codeId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public Long getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_code.codeId
     *
     * @param codeid the value for tbl_book_code.codeId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setCodeid(Long codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_code.code
     *
     * @return the value of tbl_book_code.code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_code.code
     *
     * @param code the value for tbl_book_code.code
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_code.description
     *
     * @return the value of tbl_book_code.description
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_code.description
     *
     * @param description the value for tbl_book_code.description
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_code.creatby
     *
     * @return the value of tbl_book_code.creatby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public String getCreatby() {
        return creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_code.creatby
     *
     * @param creatby the value for tbl_book_code.creatby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setCreatby(String creatby) {
        this.creatby = creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_code.creatTime
     *
     * @return the value of tbl_book_code.creatTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_code.creatTime
     *
     * @param creattime the value for tbl_book_code.creatTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_code.updateby
     *
     * @return the value of tbl_book_code.updateby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_code.updateby
     *
     * @param updateby the value for tbl_book_code.updateby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_code.updateTime
     *
     * @return the value of tbl_book_code.updateTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_code.updateTime
     *
     * @param updatetime the value for tbl_book_code.updateTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}