package com.lhzl.drp.model;

import java.util.Date;

public class BookValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_value.valueId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private Long valueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_value.codeId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private Long codeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_value.value
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_value.description
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_value.creatby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private String creatby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_value.creatTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_value.updateby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book_value.updateTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_value.valueId
     *
     * @return the value of tbl_book_value.valueId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public Long getValueid() {
        return valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_value.valueId
     *
     * @param valueid the value for tbl_book_value.valueId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setValueid(Long valueid) {
        this.valueid = valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_value.codeId
     *
     * @return the value of tbl_book_value.codeId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public Long getCodeid() {
        return codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_value.codeId
     *
     * @param codeid the value for tbl_book_value.codeId
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setCodeid(Long codeid) {
        this.codeid = codeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_value.value
     *
     * @return the value of tbl_book_value.value
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_value.value
     *
     * @param value the value for tbl_book_value.value
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_value.description
     *
     * @return the value of tbl_book_value.description
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_value.description
     *
     * @param description the value for tbl_book_value.description
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_value.creatby
     *
     * @return the value of tbl_book_value.creatby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public String getCreatby() {
        return creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_value.creatby
     *
     * @param creatby the value for tbl_book_value.creatby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setCreatby(String creatby) {
        this.creatby = creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_value.creatTime
     *
     * @return the value of tbl_book_value.creatTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_value.creatTime
     *
     * @param creattime the value for tbl_book_value.creatTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_value.updateby
     *
     * @return the value of tbl_book_value.updateby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_value.updateby
     *
     * @param updateby the value for tbl_book_value.updateby
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book_value.updateTime
     *
     * @return the value of tbl_book_value.updateTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book_value.updateTime
     *
     * @param updatetime the value for tbl_book_value.updateTime
     *
     * @mbggenerated Wed Mar 30 15:46:10 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}