package com.lhzl.drp.model;

public class ExtendinfoWithBLOBs extends Extendinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.remind
     *
     * @mbggenerated
     */
    private String remind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.lineFeature
     *
     * @mbggenerated
     */
    private String linefeature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.include
     *
     * @mbggenerated
     */
    private String include;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.notInclude
     *
     * @mbggenerated
     */
    private String notinclude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.shopping
     *
     * @mbggenerated
     */
    private String shopping;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.remind
     *
     * @return the value of tbl_extendinfo.remind
     *
     * @mbggenerated
     */
    public String getRemind() {
        return remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.remind
     *
     * @param remind the value for tbl_extendinfo.remind
     *
     * @mbggenerated
     */
    public void setRemind(String remind) {
        this.remind = remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.lineFeature
     *
     * @return the value of tbl_extendinfo.lineFeature
     *
     * @mbggenerated
     */
    public String getLinefeature() {
        return linefeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.lineFeature
     *
     * @param linefeature the value for tbl_extendinfo.lineFeature
     *
     * @mbggenerated
     */
    public void setLinefeature(String linefeature) {
        this.linefeature = linefeature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.include
     *
     * @return the value of tbl_extendinfo.include
     *
     * @mbggenerated
     */
    public String getInclude() {
        return include;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.include
     *
     * @param include the value for tbl_extendinfo.include
     *
     * @mbggenerated
     */
    public void setInclude(String include) {
        this.include = include;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.notInclude
     *
     * @return the value of tbl_extendinfo.notInclude
     *
     * @mbggenerated
     */
    public String getNotinclude() {
        return notinclude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.notInclude
     *
     * @param notinclude the value for tbl_extendinfo.notInclude
     *
     * @mbggenerated
     */
    public void setNotinclude(String notinclude) {
        this.notinclude = notinclude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.remarks
     *
     * @return the value of tbl_extendinfo.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.remarks
     *
     * @param remarks the value for tbl_extendinfo.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.shopping
     *
     * @return the value of tbl_extendinfo.shopping
     *
     * @mbggenerated
     */
    public String getShopping() {
        return shopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.shopping
     *
     * @param shopping the value for tbl_extendinfo.shopping
     *
     * @mbggenerated
     */
    public void setShopping(String shopping) {
        this.shopping = shopping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.note
     *
     * @return the value of tbl_extendinfo.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.note
     *
     * @param note the value for tbl_extendinfo.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }
}