package com.lhzl.drp.model;

import java.util.Date;

public class Extendinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.extendId
     *
     * @mbggenerated
     */
    private Long extendid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.lineId
     *
     * @mbggenerated
     */
    private Long lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.creatby
     *
     * @mbggenerated
     */
    private String creatby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.creatTime
     *
     * @mbggenerated
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_extendinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.extendId
     *
     * @return the value of tbl_extendinfo.extendId
     *
     * @mbggenerated
     */
    public Long getExtendid() {
        return extendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.extendId
     *
     * @param extendid the value for tbl_extendinfo.extendId
     *
     * @mbggenerated
     */
    public void setExtendid(Long extendid) {
        this.extendid = extendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.lineId
     *
     * @return the value of tbl_extendinfo.lineId
     *
     * @mbggenerated
     */
    public Long getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.lineId
     *
     * @param lineid the value for tbl_extendinfo.lineId
     *
     * @mbggenerated
     */
    public void setLineid(Long lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.creatby
     *
     * @return the value of tbl_extendinfo.creatby
     *
     * @mbggenerated
     */
    public String getCreatby() {
        return creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.creatby
     *
     * @param creatby the value for tbl_extendinfo.creatby
     *
     * @mbggenerated
     */
    public void setCreatby(String creatby) {
        this.creatby = creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.creatTime
     *
     * @return the value of tbl_extendinfo.creatTime
     *
     * @mbggenerated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.creatTime
     *
     * @param creattime the value for tbl_extendinfo.creatTime
     *
     * @mbggenerated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.updateby
     *
     * @return the value of tbl_extendinfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.updateby
     *
     * @param updateby the value for tbl_extendinfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_extendinfo.updateTime
     *
     * @return the value of tbl_extendinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_extendinfo.updateTime
     *
     * @param updatetime the value for tbl_extendinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}