package com.lhzl.drp.model;

import java.util.Date;

public class Groupinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.groupId
     *
     * @mbggenerated
     */
    private Long groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.groupNo
     *
     * @mbggenerated
     */
    private String groupno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.lineId
     *
     * @mbggenerated
     */
    private Long lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.groupName
     *
     * @mbggenerated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.groupStart
     *
     * @mbggenerated
     */
    private Date groupstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.groupEnd
     *
     * @mbggenerated
     */
    private Date groupend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_groupinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.groupId
     *
     * @return the value of tbl_groupinfo.groupId
     *
     * @mbggenerated
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.groupId
     *
     * @param groupid the value for tbl_groupinfo.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.groupNo
     *
     * @return the value of tbl_groupinfo.groupNo
     *
     * @mbggenerated
     */
    public String getGroupno() {
        return groupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.groupNo
     *
     * @param groupno the value for tbl_groupinfo.groupNo
     *
     * @mbggenerated
     */
    public void setGroupno(String groupno) {
        this.groupno = groupno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.lineId
     *
     * @return the value of tbl_groupinfo.lineId
     *
     * @mbggenerated
     */
    public Long getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.lineId
     *
     * @param lineid the value for tbl_groupinfo.lineId
     *
     * @mbggenerated
     */
    public void setLineid(Long lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.groupName
     *
     * @return the value of tbl_groupinfo.groupName
     *
     * @mbggenerated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.groupName
     *
     * @param groupname the value for tbl_groupinfo.groupName
     *
     * @mbggenerated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.groupStart
     *
     * @return the value of tbl_groupinfo.groupStart
     *
     * @mbggenerated
     */
    public Date getGroupstart() {
        return groupstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.groupStart
     *
     * @param groupstart the value for tbl_groupinfo.groupStart
     *
     * @mbggenerated
     */
    public void setGroupstart(Date groupstart) {
        this.groupstart = groupstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.groupEnd
     *
     * @return the value of tbl_groupinfo.groupEnd
     *
     * @mbggenerated
     */
    public Date getGroupend() {
        return groupend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.groupEnd
     *
     * @param groupend the value for tbl_groupinfo.groupEnd
     *
     * @mbggenerated
     */
    public void setGroupend(Date groupend) {
        this.groupend = groupend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.status
     *
     * @return the value of tbl_groupinfo.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.status
     *
     * @param status the value for tbl_groupinfo.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.createby
     *
     * @return the value of tbl_groupinfo.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.createby
     *
     * @param createby the value for tbl_groupinfo.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.createTime
     *
     * @return the value of tbl_groupinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.createTime
     *
     * @param createtime the value for tbl_groupinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.updateby
     *
     * @return the value of tbl_groupinfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.updateby
     *
     * @param updateby the value for tbl_groupinfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_groupinfo.updateTime
     *
     * @return the value of tbl_groupinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_groupinfo.updateTime
     *
     * @param updatetime the value for tbl_groupinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}