package com.lhzl.drp.model;

import java.util.Date;

public class Hotelinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hotelinfo.hotelId
     *
     * @mbggenerated
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hotelinfo.hotelType
     *
     * @mbggenerated
     */
    private String hoteltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hotelinfo.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hotelinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hotelinfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_hotelinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hotelinfo.hotelId
     *
     * @return the value of tbl_hotelinfo.hotelId
     *
     * @mbggenerated
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hotelinfo.hotelId
     *
     * @param hotelid the value for tbl_hotelinfo.hotelId
     *
     * @mbggenerated
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hotelinfo.hotelType
     *
     * @return the value of tbl_hotelinfo.hotelType
     *
     * @mbggenerated
     */
    public String getHoteltype() {
        return hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hotelinfo.hotelType
     *
     * @param hoteltype the value for tbl_hotelinfo.hotelType
     *
     * @mbggenerated
     */
    public void setHoteltype(String hoteltype) {
        this.hoteltype = hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hotelinfo.createby
     *
     * @return the value of tbl_hotelinfo.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hotelinfo.createby
     *
     * @param createby the value for tbl_hotelinfo.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hotelinfo.createTime
     *
     * @return the value of tbl_hotelinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hotelinfo.createTime
     *
     * @param createtime the value for tbl_hotelinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hotelinfo.updateby
     *
     * @return the value of tbl_hotelinfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hotelinfo.updateby
     *
     * @param updateby the value for tbl_hotelinfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_hotelinfo.updateTime
     *
     * @return the value of tbl_hotelinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_hotelinfo.updateTime
     *
     * @param updatetime the value for tbl_hotelinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}