package com.lhzl.drp.model;

import java.util.Date;

public class Keywords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_keywords.keyId
     *
     * @mbggenerated
     */
    private Long keyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_keywords.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_keywords.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_keywords.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_keywords.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_keywords.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_keywords.keyId
     *
     * @return the value of tbl_keywords.keyId
     *
     * @mbggenerated
     */
    public Long getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_keywords.keyId
     *
     * @param keyid the value for tbl_keywords.keyId
     *
     * @mbggenerated
     */
    public void setKeyid(Long keyid) {
        this.keyid = keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_keywords.keywords
     *
     * @return the value of tbl_keywords.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_keywords.keywords
     *
     * @param keywords the value for tbl_keywords.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_keywords.createby
     *
     * @return the value of tbl_keywords.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_keywords.createby
     *
     * @param createby the value for tbl_keywords.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_keywords.createTime
     *
     * @return the value of tbl_keywords.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_keywords.createTime
     *
     * @param createtime the value for tbl_keywords.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_keywords.updateby
     *
     * @return the value of tbl_keywords.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_keywords.updateby
     *
     * @param updateby the value for tbl_keywords.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_keywords.updateTime
     *
     * @return the value of tbl_keywords.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_keywords.updateTime
     *
     * @param updatetime the value for tbl_keywords.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}