package com.lhzl.drp.model;

import java.util.Date;

public class Lineinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.lineId
     *
     * @mbggenerated
     */
    private Long lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.lineType
     *
     * @mbggenerated
     */
    private String linetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.tourType
     *
     * @mbggenerated
     */
    private String tourtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.lineNo
     *
     * @mbggenerated
     */
    private String lineno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.sysNO
     *
     * @mbggenerated
     */
    private String sysno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.lineStart
     *
     * @mbggenerated
     */
    private Long linestart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.lineEnd
     *
     * @mbggenerated
     */
    private Long lineend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.subTitile
     *
     * @mbggenerated
     */
    private String subtitile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.lineSid
     *
     * @mbggenerated
     */
    private String linesid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.keyword
     *
     * @mbggenerated
     */
    private Long keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.days
     *
     * @mbggenerated
     */
    private Integer days;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.hotelDays
     *
     * @mbggenerated
     */
    private Integer hoteldays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.hotelType
     *
     * @mbggenerated
     */
    private Integer hoteltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.hotelName
     *
     * @mbggenerated
     */
    private String hotelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.deadline
     *
     * @mbggenerated
     */
    private String deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.hasWeekend
     *
     * @mbggenerated
     */
    private String hasweekend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.cusSelect
     *
     * @mbggenerated
     */
    private String cusselect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.min
     *
     * @mbggenerated
     */
    private Integer min;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.hasConfirm
     *
     * @mbggenerated
     */
    private String hasconfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.creatby
     *
     * @mbggenerated
     */
    private String creatby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_lineinfo.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.lineId
     *
     * @return the value of tbl_lineinfo.lineId
     *
     * @mbggenerated
     */
    public Long getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.lineId
     *
     * @param lineid the value for tbl_lineinfo.lineId
     *
     * @mbggenerated
     */
    public void setLineid(Long lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.lineType
     *
     * @return the value of tbl_lineinfo.lineType
     *
     * @mbggenerated
     */
    public String getLinetype() {
        return linetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.lineType
     *
     * @param linetype the value for tbl_lineinfo.lineType
     *
     * @mbggenerated
     */
    public void setLinetype(String linetype) {
        this.linetype = linetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.tourType
     *
     * @return the value of tbl_lineinfo.tourType
     *
     * @mbggenerated
     */
    public String getTourtype() {
        return tourtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.tourType
     *
     * @param tourtype the value for tbl_lineinfo.tourType
     *
     * @mbggenerated
     */
    public void setTourtype(String tourtype) {
        this.tourtype = tourtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.lineNo
     *
     * @return the value of tbl_lineinfo.lineNo
     *
     * @mbggenerated
     */
    public String getLineno() {
        return lineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.lineNo
     *
     * @param lineno the value for tbl_lineinfo.lineNo
     *
     * @mbggenerated
     */
    public void setLineno(String lineno) {
        this.lineno = lineno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.sysNO
     *
     * @return the value of tbl_lineinfo.sysNO
     *
     * @mbggenerated
     */
    public String getSysno() {
        return sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.sysNO
     *
     * @param sysno the value for tbl_lineinfo.sysNO
     *
     * @mbggenerated
     */
    public void setSysno(String sysno) {
        this.sysno = sysno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.lineStart
     *
     * @return the value of tbl_lineinfo.lineStart
     *
     * @mbggenerated
     */
    public Long getLinestart() {
        return linestart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.lineStart
     *
     * @param linestart the value for tbl_lineinfo.lineStart
     *
     * @mbggenerated
     */
    public void setLinestart(Long linestart) {
        this.linestart = linestart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.lineEnd
     *
     * @return the value of tbl_lineinfo.lineEnd
     *
     * @mbggenerated
     */
    public Long getLineend() {
        return lineend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.lineEnd
     *
     * @param lineend the value for tbl_lineinfo.lineEnd
     *
     * @mbggenerated
     */
    public void setLineend(Long lineend) {
        this.lineend = lineend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.title
     *
     * @return the value of tbl_lineinfo.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.title
     *
     * @param title the value for tbl_lineinfo.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.subTitile
     *
     * @return the value of tbl_lineinfo.subTitile
     *
     * @mbggenerated
     */
    public String getSubtitile() {
        return subtitile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.subTitile
     *
     * @param subtitile the value for tbl_lineinfo.subTitile
     *
     * @mbggenerated
     */
    public void setSubtitile(String subtitile) {
        this.subtitile = subtitile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.lineSid
     *
     * @return the value of tbl_lineinfo.lineSid
     *
     * @mbggenerated
     */
    public String getLinesid() {
        return linesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.lineSid
     *
     * @param linesid the value for tbl_lineinfo.lineSid
     *
     * @mbggenerated
     */
    public void setLinesid(String linesid) {
        this.linesid = linesid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.keyword
     *
     * @return the value of tbl_lineinfo.keyword
     *
     * @mbggenerated
     */
    public Long getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.keyword
     *
     * @param keyword the value for tbl_lineinfo.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(Long keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.days
     *
     * @return the value of tbl_lineinfo.days
     *
     * @mbggenerated
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.days
     *
     * @param days the value for tbl_lineinfo.days
     *
     * @mbggenerated
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.hotelDays
     *
     * @return the value of tbl_lineinfo.hotelDays
     *
     * @mbggenerated
     */
    public Integer getHoteldays() {
        return hoteldays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.hotelDays
     *
     * @param hoteldays the value for tbl_lineinfo.hotelDays
     *
     * @mbggenerated
     */
    public void setHoteldays(Integer hoteldays) {
        this.hoteldays = hoteldays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.hotelType
     *
     * @return the value of tbl_lineinfo.hotelType
     *
     * @mbggenerated
     */
    public Integer getHoteltype() {
        return hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.hotelType
     *
     * @param hoteltype the value for tbl_lineinfo.hotelType
     *
     * @mbggenerated
     */
    public void setHoteltype(Integer hoteltype) {
        this.hoteltype = hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.hotelName
     *
     * @return the value of tbl_lineinfo.hotelName
     *
     * @mbggenerated
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.hotelName
     *
     * @param hotelname the value for tbl_lineinfo.hotelName
     *
     * @mbggenerated
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.tel
     *
     * @return the value of tbl_lineinfo.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.tel
     *
     * @param tel the value for tbl_lineinfo.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.deadline
     *
     * @return the value of tbl_lineinfo.deadline
     *
     * @mbggenerated
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.deadline
     *
     * @param deadline the value for tbl_lineinfo.deadline
     *
     * @mbggenerated
     */
    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.hasWeekend
     *
     * @return the value of tbl_lineinfo.hasWeekend
     *
     * @mbggenerated
     */
    public String getHasweekend() {
        return hasweekend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.hasWeekend
     *
     * @param hasweekend the value for tbl_lineinfo.hasWeekend
     *
     * @mbggenerated
     */
    public void setHasweekend(String hasweekend) {
        this.hasweekend = hasweekend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.cusSelect
     *
     * @return the value of tbl_lineinfo.cusSelect
     *
     * @mbggenerated
     */
    public String getCusselect() {
        return cusselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.cusSelect
     *
     * @param cusselect the value for tbl_lineinfo.cusSelect
     *
     * @mbggenerated
     */
    public void setCusselect(String cusselect) {
        this.cusselect = cusselect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.min
     *
     * @return the value of tbl_lineinfo.min
     *
     * @mbggenerated
     */
    public Integer getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.min
     *
     * @param min the value for tbl_lineinfo.min
     *
     * @mbggenerated
     */
    public void setMin(Integer min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.hasConfirm
     *
     * @return the value of tbl_lineinfo.hasConfirm
     *
     * @mbggenerated
     */
    public String getHasconfirm() {
        return hasconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.hasConfirm
     *
     * @param hasconfirm the value for tbl_lineinfo.hasConfirm
     *
     * @mbggenerated
     */
    public void setHasconfirm(String hasconfirm) {
        this.hasconfirm = hasconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.status
     *
     * @return the value of tbl_lineinfo.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.status
     *
     * @param status the value for tbl_lineinfo.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.creatby
     *
     * @return the value of tbl_lineinfo.creatby
     *
     * @mbggenerated
     */
    public String getCreatby() {
        return creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.creatby
     *
     * @param creatby the value for tbl_lineinfo.creatby
     *
     * @mbggenerated
     */
    public void setCreatby(String creatby) {
        this.creatby = creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.createTime
     *
     * @return the value of tbl_lineinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.createTime
     *
     * @param createtime the value for tbl_lineinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.updateby
     *
     * @return the value of tbl_lineinfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.updateby
     *
     * @param updateby the value for tbl_lineinfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.updateTime
     *
     * @return the value of tbl_lineinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.updateTime
     *
     * @param updatetime the value for tbl_lineinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_lineinfo.desc
     *
     * @return the value of tbl_lineinfo.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_lineinfo.desc
     *
     * @param desc the value for tbl_lineinfo.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}