package com.lhzl.drp.model;

import java.util.Date;

public class Loginfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_loginfo.logId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Long logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_loginfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_loginfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_loginfo.logCont
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String logcont;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_loginfo.logId
     *
     * @return the value of tbl_loginfo.logId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Long getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_loginfo.logId
     *
     * @param logid the value for tbl_loginfo.logId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setLogid(Long logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_loginfo.createby
     *
     * @return the value of tbl_loginfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_loginfo.createby
     *
     * @param createby the value for tbl_loginfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_loginfo.createTime
     *
     * @return the value of tbl_loginfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_loginfo.createTime
     *
     * @param createtime the value for tbl_loginfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_loginfo.logCont
     *
     * @return the value of tbl_loginfo.logCont
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getLogcont() {
        return logcont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_loginfo.logCont
     *
     * @param logcont the value for tbl_loginfo.logCont
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setLogcont(String logcont) {
        this.logcont = logcont;
    }
}