package com.lhzl.drp.model;

import java.util.Date;

public class Messageinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_messageinfo.msgId
     *
     * @mbggenerated
     */
    private Long msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_messageinfo.msgType
     *
     * @mbggenerated
     */
    private String msgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_messageinfo.isRead
     *
     * @mbggenerated
     */
    private String isread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_messageinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_messageinfo.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_messageinfo.msgId
     *
     * @return the value of tbl_messageinfo.msgId
     *
     * @mbggenerated
     */
    public Long getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_messageinfo.msgId
     *
     * @param msgid the value for tbl_messageinfo.msgId
     *
     * @mbggenerated
     */
    public void setMsgid(Long msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_messageinfo.msgType
     *
     * @return the value of tbl_messageinfo.msgType
     *
     * @mbggenerated
     */
    public String getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_messageinfo.msgType
     *
     * @param msgtype the value for tbl_messageinfo.msgType
     *
     * @mbggenerated
     */
    public void setMsgtype(String msgtype) {
        this.msgtype = msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_messageinfo.isRead
     *
     * @return the value of tbl_messageinfo.isRead
     *
     * @mbggenerated
     */
    public String getIsread() {
        return isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_messageinfo.isRead
     *
     * @param isread the value for tbl_messageinfo.isRead
     *
     * @mbggenerated
     */
    public void setIsread(String isread) {
        this.isread = isread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_messageinfo.createTime
     *
     * @return the value of tbl_messageinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_messageinfo.createTime
     *
     * @param createtime the value for tbl_messageinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_messageinfo.message
     *
     * @return the value of tbl_messageinfo.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_messageinfo.message
     *
     * @param message the value for tbl_messageinfo.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }
}