package com.lhzl.drp.model;

import java.util.Date;

public class Operatorinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.operId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Long operid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.userId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.opacct
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String opacct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.operpwd
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String operpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.operName
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String opername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.gender
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.restTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Date resttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.retryCount
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Integer retrycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.status
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.lastLoginTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.lastLoginIp
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String lastloginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.updateby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_operatorinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.operId
     *
     * @return the value of tbl_operatorinfo.operId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Long getOperid() {
        return operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.operId
     *
     * @param operid the value for tbl_operatorinfo.operId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setOperid(Long operid) {
        this.operid = operid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.userId
     *
     * @return the value of tbl_operatorinfo.userId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.userId
     *
     * @param userid the value for tbl_operatorinfo.userId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.opacct
     *
     * @return the value of tbl_operatorinfo.opacct
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getOpacct() {
        return opacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.opacct
     *
     * @param opacct the value for tbl_operatorinfo.opacct
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setOpacct(String opacct) {
        this.opacct = opacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.operpwd
     *
     * @return the value of tbl_operatorinfo.operpwd
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getOperpwd() {
        return operpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.operpwd
     *
     * @param operpwd the value for tbl_operatorinfo.operpwd
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setOperpwd(String operpwd) {
        this.operpwd = operpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.operName
     *
     * @return the value of tbl_operatorinfo.operName
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getOpername() {
        return opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.operName
     *
     * @param opername the value for tbl_operatorinfo.operName
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setOpername(String opername) {
        this.opername = opername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.gender
     *
     * @return the value of tbl_operatorinfo.gender
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.gender
     *
     * @param gender the value for tbl_operatorinfo.gender
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.restTime
     *
     * @return the value of tbl_operatorinfo.restTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Date getResttime() {
        return resttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.restTime
     *
     * @param resttime the value for tbl_operatorinfo.restTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setResttime(Date resttime) {
        this.resttime = resttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.retryCount
     *
     * @return the value of tbl_operatorinfo.retryCount
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Integer getRetrycount() {
        return retrycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.retryCount
     *
     * @param retrycount the value for tbl_operatorinfo.retryCount
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setRetrycount(Integer retrycount) {
        this.retrycount = retrycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.status
     *
     * @return the value of tbl_operatorinfo.status
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.status
     *
     * @param status the value for tbl_operatorinfo.status
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.lastLoginTime
     *
     * @return the value of tbl_operatorinfo.lastLoginTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.lastLoginTime
     *
     * @param lastlogintime the value for tbl_operatorinfo.lastLoginTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.lastLoginIp
     *
     * @return the value of tbl_operatorinfo.lastLoginIp
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getLastloginip() {
        return lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.lastLoginIp
     *
     * @param lastloginip the value for tbl_operatorinfo.lastLoginIp
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setLastloginip(String lastloginip) {
        this.lastloginip = lastloginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.createby
     *
     * @return the value of tbl_operatorinfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.createby
     *
     * @param createby the value for tbl_operatorinfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.createTime
     *
     * @return the value of tbl_operatorinfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.createTime
     *
     * @param createtime the value for tbl_operatorinfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.updateby
     *
     * @return the value of tbl_operatorinfo.updateby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.updateby
     *
     * @param updateby the value for tbl_operatorinfo.updateby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_operatorinfo.updateTime
     *
     * @return the value of tbl_operatorinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_operatorinfo.updateTime
     *
     * @param updatetime the value for tbl_operatorinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}