package com.lhzl.drp.model;

import java.math.BigDecimal;
import java.util.Date;

public class Orderinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.orderId
     *
     * @mbggenerated
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.orderNo
     *
     * @mbggenerated
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.lineId
     *
     * @mbggenerated
     */
    private Long lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.drpid
     *
     * @mbggenerated
     */
    private Long drpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.ordamt
     *
     * @mbggenerated
     */
    private BigDecimal ordamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.orderTime
     *
     * @mbggenerated
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_orderinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.orderId
     *
     * @return the value of tbl_orderinfo.orderId
     *
     * @mbggenerated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.orderId
     *
     * @param orderid the value for tbl_orderinfo.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.orderNo
     *
     * @return the value of tbl_orderinfo.orderNo
     *
     * @mbggenerated
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.orderNo
     *
     * @param orderno the value for tbl_orderinfo.orderNo
     *
     * @mbggenerated
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.lineId
     *
     * @return the value of tbl_orderinfo.lineId
     *
     * @mbggenerated
     */
    public Long getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.lineId
     *
     * @param lineid the value for tbl_orderinfo.lineId
     *
     * @mbggenerated
     */
    public void setLineid(Long lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.drpid
     *
     * @return the value of tbl_orderinfo.drpid
     *
     * @mbggenerated
     */
    public Long getDrpid() {
        return drpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.drpid
     *
     * @param drpid the value for tbl_orderinfo.drpid
     *
     * @mbggenerated
     */
    public void setDrpid(Long drpid) {
        this.drpid = drpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.ordamt
     *
     * @return the value of tbl_orderinfo.ordamt
     *
     * @mbggenerated
     */
    public BigDecimal getOrdamt() {
        return ordamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.ordamt
     *
     * @param ordamt the value for tbl_orderinfo.ordamt
     *
     * @mbggenerated
     */
    public void setOrdamt(BigDecimal ordamt) {
        this.ordamt = ordamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.startTime
     *
     * @return the value of tbl_orderinfo.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.startTime
     *
     * @param starttime the value for tbl_orderinfo.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.status
     *
     * @return the value of tbl_orderinfo.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.status
     *
     * @param status the value for tbl_orderinfo.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.orderTime
     *
     * @return the value of tbl_orderinfo.orderTime
     *
     * @mbggenerated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.orderTime
     *
     * @param ordertime the value for tbl_orderinfo.orderTime
     *
     * @mbggenerated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.createby
     *
     * @return the value of tbl_orderinfo.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.createby
     *
     * @param createby the value for tbl_orderinfo.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.createTime
     *
     * @return the value of tbl_orderinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.createTime
     *
     * @param createtime the value for tbl_orderinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.updateby
     *
     * @return the value of tbl_orderinfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.updateby
     *
     * @param updateby the value for tbl_orderinfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_orderinfo.updateTime
     *
     * @return the value of tbl_orderinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_orderinfo.updateTime
     *
     * @param updatetime the value for tbl_orderinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}