package com.lhzl.drp.model;

import java.math.BigDecimal;
import java.util.Date;

public class Payinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.payId
     *
     * @mbggenerated
     */
    private Long payid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.payNo
     *
     * @mbggenerated
     */
    private String payno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.cusNo
     *
     * @mbggenerated
     */
    private String cusno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.orderId
     *
     * @mbggenerated
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.orderAmt
     *
     * @mbggenerated
     */
    private BigDecimal orderamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.payAmt
     *
     * @mbggenerated
     */
    private BigDecimal payamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.prepaidAmt
     *
     * @mbggenerated
     */
    private BigDecimal prepaidamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.prepaidTime
     *
     * @mbggenerated
     */
    private Date prepaidtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.finalAmt
     *
     * @mbggenerated
     */
    private BigDecimal finalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.finalTime
     *
     * @mbggenerated
     */
    private Date finaltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.payer
     *
     * @mbggenerated
     */
    private String payer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.payTime
     *
     * @mbggenerated
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_payinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.payId
     *
     * @return the value of tbl_payinfo.payId
     *
     * @mbggenerated
     */
    public Long getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.payId
     *
     * @param payid the value for tbl_payinfo.payId
     *
     * @mbggenerated
     */
    public void setPayid(Long payid) {
        this.payid = payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.payNo
     *
     * @return the value of tbl_payinfo.payNo
     *
     * @mbggenerated
     */
    public String getPayno() {
        return payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.payNo
     *
     * @param payno the value for tbl_payinfo.payNo
     *
     * @mbggenerated
     */
    public void setPayno(String payno) {
        this.payno = payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.cusNo
     *
     * @return the value of tbl_payinfo.cusNo
     *
     * @mbggenerated
     */
    public String getCusno() {
        return cusno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.cusNo
     *
     * @param cusno the value for tbl_payinfo.cusNo
     *
     * @mbggenerated
     */
    public void setCusno(String cusno) {
        this.cusno = cusno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.orderId
     *
     * @return the value of tbl_payinfo.orderId
     *
     * @mbggenerated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.orderId
     *
     * @param orderid the value for tbl_payinfo.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.orderAmt
     *
     * @return the value of tbl_payinfo.orderAmt
     *
     * @mbggenerated
     */
    public BigDecimal getOrderamt() {
        return orderamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.orderAmt
     *
     * @param orderamt the value for tbl_payinfo.orderAmt
     *
     * @mbggenerated
     */
    public void setOrderamt(BigDecimal orderamt) {
        this.orderamt = orderamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.payAmt
     *
     * @return the value of tbl_payinfo.payAmt
     *
     * @mbggenerated
     */
    public BigDecimal getPayamt() {
        return payamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.payAmt
     *
     * @param payamt the value for tbl_payinfo.payAmt
     *
     * @mbggenerated
     */
    public void setPayamt(BigDecimal payamt) {
        this.payamt = payamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.prepaidAmt
     *
     * @return the value of tbl_payinfo.prepaidAmt
     *
     * @mbggenerated
     */
    public BigDecimal getPrepaidamt() {
        return prepaidamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.prepaidAmt
     *
     * @param prepaidamt the value for tbl_payinfo.prepaidAmt
     *
     * @mbggenerated
     */
    public void setPrepaidamt(BigDecimal prepaidamt) {
        this.prepaidamt = prepaidamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.prepaidTime
     *
     * @return the value of tbl_payinfo.prepaidTime
     *
     * @mbggenerated
     */
    public Date getPrepaidtime() {
        return prepaidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.prepaidTime
     *
     * @param prepaidtime the value for tbl_payinfo.prepaidTime
     *
     * @mbggenerated
     */
    public void setPrepaidtime(Date prepaidtime) {
        this.prepaidtime = prepaidtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.finalAmt
     *
     * @return the value of tbl_payinfo.finalAmt
     *
     * @mbggenerated
     */
    public BigDecimal getFinalamt() {
        return finalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.finalAmt
     *
     * @param finalamt the value for tbl_payinfo.finalAmt
     *
     * @mbggenerated
     */
    public void setFinalamt(BigDecimal finalamt) {
        this.finalamt = finalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.finalTime
     *
     * @return the value of tbl_payinfo.finalTime
     *
     * @mbggenerated
     */
    public Date getFinaltime() {
        return finaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.finalTime
     *
     * @param finaltime the value for tbl_payinfo.finalTime
     *
     * @mbggenerated
     */
    public void setFinaltime(Date finaltime) {
        this.finaltime = finaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.payer
     *
     * @return the value of tbl_payinfo.payer
     *
     * @mbggenerated
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.payer
     *
     * @param payer the value for tbl_payinfo.payer
     *
     * @mbggenerated
     */
    public void setPayer(String payer) {
        this.payer = payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.payTime
     *
     * @return the value of tbl_payinfo.payTime
     *
     * @mbggenerated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.payTime
     *
     * @param paytime the value for tbl_payinfo.payTime
     *
     * @mbggenerated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.status
     *
     * @return the value of tbl_payinfo.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.status
     *
     * @param status the value for tbl_payinfo.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.createby
     *
     * @return the value of tbl_payinfo.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.createby
     *
     * @param createby the value for tbl_payinfo.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.createTime
     *
     * @return the value of tbl_payinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.createTime
     *
     * @param createtime the value for tbl_payinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.updateby
     *
     * @return the value of tbl_payinfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.updateby
     *
     * @param updateby the value for tbl_payinfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_payinfo.updateTime
     *
     * @return the value of tbl_payinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_payinfo.updateTime
     *
     * @param updatetime the value for tbl_payinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}