package com.lhzl.drp.model;

import java.util.Date;

public class Permissioninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permissioninfo.pmsnId
     *
     * @mbggenerated
     */
    private Long pmsnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permissioninfo.pmsnName
     *
     * @mbggenerated
     */
    private String pmsnname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permissioninfo.actionName
     *
     * @mbggenerated
     */
    private String actionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permissioninfo.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permissioninfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permissioninfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permissioninfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_permissioninfo.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permissioninfo.pmsnId
     *
     * @return the value of tbl_permissioninfo.pmsnId
     *
     * @mbggenerated
     */
    public Long getPmsnid() {
        return pmsnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permissioninfo.pmsnId
     *
     * @param pmsnid the value for tbl_permissioninfo.pmsnId
     *
     * @mbggenerated
     */
    public void setPmsnid(Long pmsnid) {
        this.pmsnid = pmsnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permissioninfo.pmsnName
     *
     * @return the value of tbl_permissioninfo.pmsnName
     *
     * @mbggenerated
     */
    public String getPmsnname() {
        return pmsnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permissioninfo.pmsnName
     *
     * @param pmsnname the value for tbl_permissioninfo.pmsnName
     *
     * @mbggenerated
     */
    public void setPmsnname(String pmsnname) {
        this.pmsnname = pmsnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permissioninfo.actionName
     *
     * @return the value of tbl_permissioninfo.actionName
     *
     * @mbggenerated
     */
    public String getActionname() {
        return actionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permissioninfo.actionName
     *
     * @param actionname the value for tbl_permissioninfo.actionName
     *
     * @mbggenerated
     */
    public void setActionname(String actionname) {
        this.actionname = actionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permissioninfo.createby
     *
     * @return the value of tbl_permissioninfo.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permissioninfo.createby
     *
     * @param createby the value for tbl_permissioninfo.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permissioninfo.createTime
     *
     * @return the value of tbl_permissioninfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permissioninfo.createTime
     *
     * @param createtime the value for tbl_permissioninfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permissioninfo.updateby
     *
     * @return the value of tbl_permissioninfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permissioninfo.updateby
     *
     * @param updateby the value for tbl_permissioninfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permissioninfo.updateTime
     *
     * @return the value of tbl_permissioninfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permissioninfo.updateTime
     *
     * @param updatetime the value for tbl_permissioninfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_permissioninfo.remark
     *
     * @return the value of tbl_permissioninfo.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_permissioninfo.remark
     *
     * @param remark the value for tbl_permissioninfo.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}