package com.lhzl.drp.model;

import java.util.Date;

public class Roleinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_roleinfo.roleId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_roleinfo.roleName
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_roleinfo.creatby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String creatby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_roleinfo.creatTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_roleinfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_roleinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_roleinfo.remark
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_roleinfo.roleId
     *
     * @return the value of tbl_roleinfo.roleId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_roleinfo.roleId
     *
     * @param roleid the value for tbl_roleinfo.roleId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_roleinfo.roleName
     *
     * @return the value of tbl_roleinfo.roleName
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_roleinfo.roleName
     *
     * @param rolename the value for tbl_roleinfo.roleName
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_roleinfo.creatby
     *
     * @return the value of tbl_roleinfo.creatby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getCreatby() {
        return creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_roleinfo.creatby
     *
     * @param creatby the value for tbl_roleinfo.creatby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setCreatby(String creatby) {
        this.creatby = creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_roleinfo.creatTime
     *
     * @return the value of tbl_roleinfo.creatTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_roleinfo.creatTime
     *
     * @param creattime the value for tbl_roleinfo.creatTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_roleinfo.updateby
     *
     * @return the value of tbl_roleinfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_roleinfo.updateby
     *
     * @param updateby the value for tbl_roleinfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_roleinfo.updateTime
     *
     * @return the value of tbl_roleinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_roleinfo.updateTime
     *
     * @param updatetime the value for tbl_roleinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_roleinfo.remark
     *
     * @return the value of tbl_roleinfo.remark
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_roleinfo.remark
     *
     * @param remark the value for tbl_roleinfo.remark
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}