package com.lhzl.drp.model;

import java.util.Date;

public class Rolepmsninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepmsninfo.oprlId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Long oprlid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepmsninfo.roleid
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepmsninfo.oprtid
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Long oprtid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepmsninfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepmsninfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepmsninfo.oprlId
     *
     * @return the value of tbl_rolepmsninfo.oprlId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Long getOprlid() {
        return oprlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepmsninfo.oprlId
     *
     * @param oprlid the value for tbl_rolepmsninfo.oprlId
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setOprlid(Long oprlid) {
        this.oprlid = oprlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepmsninfo.roleid
     *
     * @return the value of tbl_rolepmsninfo.roleid
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepmsninfo.roleid
     *
     * @param roleid the value for tbl_rolepmsninfo.roleid
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepmsninfo.oprtid
     *
     * @return the value of tbl_rolepmsninfo.oprtid
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Long getOprtid() {
        return oprtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepmsninfo.oprtid
     *
     * @param oprtid the value for tbl_rolepmsninfo.oprtid
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setOprtid(Long oprtid) {
        this.oprtid = oprtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepmsninfo.createby
     *
     * @return the value of tbl_rolepmsninfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepmsninfo.createby
     *
     * @param createby the value for tbl_rolepmsninfo.createby
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepmsninfo.createTime
     *
     * @return the value of tbl_rolepmsninfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepmsninfo.createTime
     *
     * @param createtime the value for tbl_rolepmsninfo.createTime
     *
     * @mbggenerated Thu Mar 24 13:45:27 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}