package com.lhzl.drp.model;

import java.util.Date;

public class Rolepermissioninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepermissioninfo.rlpmId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Long rlpmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepermissioninfo.roleId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepermissioninfo.pmsnId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Long pmsnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepermissioninfo.createby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepermissioninfo.createTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepermissioninfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_rolepermissioninfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepermissioninfo.rlpmId
     *
     * @return the value of tbl_rolepermissioninfo.rlpmId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Long getRlpmid() {
        return rlpmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepermissioninfo.rlpmId
     *
     * @param rlpmid the value for tbl_rolepermissioninfo.rlpmId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setRlpmid(Long rlpmid) {
        this.rlpmid = rlpmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepermissioninfo.roleId
     *
     * @return the value of tbl_rolepermissioninfo.roleId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepermissioninfo.roleId
     *
     * @param roleid the value for tbl_rolepermissioninfo.roleId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepermissioninfo.pmsnId
     *
     * @return the value of tbl_rolepermissioninfo.pmsnId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Long getPmsnid() {
        return pmsnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepermissioninfo.pmsnId
     *
     * @param pmsnid the value for tbl_rolepermissioninfo.pmsnId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setPmsnid(Long pmsnid) {
        this.pmsnid = pmsnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepermissioninfo.createby
     *
     * @return the value of tbl_rolepermissioninfo.createby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepermissioninfo.createby
     *
     * @param createby the value for tbl_rolepermissioninfo.createby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepermissioninfo.createTime
     *
     * @return the value of tbl_rolepermissioninfo.createTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepermissioninfo.createTime
     *
     * @param createtime the value for tbl_rolepermissioninfo.createTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepermissioninfo.updateby
     *
     * @return the value of tbl_rolepermissioninfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepermissioninfo.updateby
     *
     * @param updateby the value for tbl_rolepermissioninfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_rolepermissioninfo.updateTime
     *
     * @return the value of tbl_rolepermissioninfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_rolepermissioninfo.updateTime
     *
     * @param updatetime the value for tbl_rolepermissioninfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}