package com.lhzl.drp.model;

import java.util.Date;

public class Shuttleinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.shuttleId
     *
     * @mbggenerated
     */
    private Long shuttleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.lineId
     *
     * @mbggenerated
     */
    private Long lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.startId
     *
     * @mbggenerated
     */
    private Long startid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.startTime
     *
     * @mbggenerated
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.trip
     *
     * @mbggenerated
     */
    private String trip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.returnTrip
     *
     * @mbggenerated
     */
    private String returntrip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_shuttleinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.shuttleId
     *
     * @return the value of tbl_shuttleinfo.shuttleId
     *
     * @mbggenerated
     */
    public Long getShuttleid() {
        return shuttleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.shuttleId
     *
     * @param shuttleid the value for tbl_shuttleinfo.shuttleId
     *
     * @mbggenerated
     */
    public void setShuttleid(Long shuttleid) {
        this.shuttleid = shuttleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.lineId
     *
     * @return the value of tbl_shuttleinfo.lineId
     *
     * @mbggenerated
     */
    public Long getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.lineId
     *
     * @param lineid the value for tbl_shuttleinfo.lineId
     *
     * @mbggenerated
     */
    public void setLineid(Long lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.startId
     *
     * @return the value of tbl_shuttleinfo.startId
     *
     * @mbggenerated
     */
    public Long getStartid() {
        return startid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.startId
     *
     * @param startid the value for tbl_shuttleinfo.startId
     *
     * @mbggenerated
     */
    public void setStartid(Long startid) {
        this.startid = startid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.startTime
     *
     * @return the value of tbl_shuttleinfo.startTime
     *
     * @mbggenerated
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.startTime
     *
     * @param starttime the value for tbl_shuttleinfo.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.trip
     *
     * @return the value of tbl_shuttleinfo.trip
     *
     * @mbggenerated
     */
    public String getTrip() {
        return trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.trip
     *
     * @param trip the value for tbl_shuttleinfo.trip
     *
     * @mbggenerated
     */
    public void setTrip(String trip) {
        this.trip = trip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.returnTrip
     *
     * @return the value of tbl_shuttleinfo.returnTrip
     *
     * @mbggenerated
     */
    public String getReturntrip() {
        return returntrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.returnTrip
     *
     * @param returntrip the value for tbl_shuttleinfo.returnTrip
     *
     * @mbggenerated
     */
    public void setReturntrip(String returntrip) {
        this.returntrip = returntrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.createby
     *
     * @return the value of tbl_shuttleinfo.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.createby
     *
     * @param createby the value for tbl_shuttleinfo.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.createTime
     *
     * @return the value of tbl_shuttleinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.createTime
     *
     * @param createtime the value for tbl_shuttleinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.updateby
     *
     * @return the value of tbl_shuttleinfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.updateby
     *
     * @param updateby the value for tbl_shuttleinfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_shuttleinfo.updateTime
     *
     * @return the value of tbl_shuttleinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_shuttleinfo.updateTime
     *
     * @param updatetime the value for tbl_shuttleinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}