package com.lhzl.drp.model;

import java.util.Date;

public class Stationinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stationinfo.stationId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Long stationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stationinfo.stationName
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stationinfo.stationType
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String stationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stationinfo.creatby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String creatby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stationinfo.createTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stationinfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_stationinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stationinfo.stationId
     *
     * @return the value of tbl_stationinfo.stationId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Long getStationid() {
        return stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stationinfo.stationId
     *
     * @param stationid the value for tbl_stationinfo.stationId
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setStationid(Long stationid) {
        this.stationid = stationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stationinfo.stationName
     *
     * @return the value of tbl_stationinfo.stationName
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stationinfo.stationName
     *
     * @param stationname the value for tbl_stationinfo.stationName
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setStationname(String stationname) {
        this.stationname = stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stationinfo.stationType
     *
     * @return the value of tbl_stationinfo.stationType
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getStationtype() {
        return stationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stationinfo.stationType
     *
     * @param stationtype the value for tbl_stationinfo.stationType
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setStationtype(String stationtype) {
        this.stationtype = stationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stationinfo.creatby
     *
     * @return the value of tbl_stationinfo.creatby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getCreatby() {
        return creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stationinfo.creatby
     *
     * @param creatby the value for tbl_stationinfo.creatby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setCreatby(String creatby) {
        this.creatby = creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stationinfo.createTime
     *
     * @return the value of tbl_stationinfo.createTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stationinfo.createTime
     *
     * @param createtime the value for tbl_stationinfo.createTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stationinfo.updateby
     *
     * @return the value of tbl_stationinfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stationinfo.updateby
     *
     * @param updateby the value for tbl_stationinfo.updateby
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_stationinfo.updateTime
     *
     * @return the value of tbl_stationinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_stationinfo.updateTime
     *
     * @param updatetime the value for tbl_stationinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 14:57:45 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}