package com.lhzl.drp.model;

import java.util.Date;

public class Themeinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_themeinfo.themeId
     *
     * @mbggenerated
     */
    private Long themeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_themeinfo.themeName
     *
     * @mbggenerated
     */
    private String themename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_themeinfo.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_themeinfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_themeinfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_themeinfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_themeinfo.themeId
     *
     * @return the value of tbl_themeinfo.themeId
     *
     * @mbggenerated
     */
    public Long getThemeid() {
        return themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_themeinfo.themeId
     *
     * @param themeid the value for tbl_themeinfo.themeId
     *
     * @mbggenerated
     */
    public void setThemeid(Long themeid) {
        this.themeid = themeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_themeinfo.themeName
     *
     * @return the value of tbl_themeinfo.themeName
     *
     * @mbggenerated
     */
    public String getThemename() {
        return themename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_themeinfo.themeName
     *
     * @param themename the value for tbl_themeinfo.themeName
     *
     * @mbggenerated
     */
    public void setThemename(String themename) {
        this.themename = themename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_themeinfo.createby
     *
     * @return the value of tbl_themeinfo.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_themeinfo.createby
     *
     * @param createby the value for tbl_themeinfo.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_themeinfo.createTime
     *
     * @return the value of tbl_themeinfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_themeinfo.createTime
     *
     * @param createtime the value for tbl_themeinfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_themeinfo.updateby
     *
     * @return the value of tbl_themeinfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_themeinfo.updateby
     *
     * @param updateby the value for tbl_themeinfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_themeinfo.updateTime
     *
     * @return the value of tbl_themeinfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_themeinfo.updateTime
     *
     * @param updatetime the value for tbl_themeinfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}