package com.lhzl.drp.model;

import java.util.Date;

public class Touristinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.touristId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private Long touristid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.groupId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private Long groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.trainId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private Long trainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.tourName
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private String tourname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.isChildren
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private String ischildren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.IDCard
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.tourSeat
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private String tourseat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.creatby
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private String creatby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.createTime
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.updateby
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_touristinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.touristId
     *
     * @return the value of tbl_touristinfo.touristId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public Long getTouristid() {
        return touristid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.touristId
     *
     * @param touristid the value for tbl_touristinfo.touristId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setTouristid(Long touristid) {
        this.touristid = touristid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.groupId
     *
     * @return the value of tbl_touristinfo.groupId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public Long getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.groupId
     *
     * @param groupid the value for tbl_touristinfo.groupId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setGroupid(Long groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.trainId
     *
     * @return the value of tbl_touristinfo.trainId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public Long getTrainid() {
        return trainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.trainId
     *
     * @param trainid the value for tbl_touristinfo.trainId
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setTrainid(Long trainid) {
        this.trainid = trainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.tourName
     *
     * @return the value of tbl_touristinfo.tourName
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public String getTourname() {
        return tourname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.tourName
     *
     * @param tourname the value for tbl_touristinfo.tourName
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setTourname(String tourname) {
        this.tourname = tourname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.isChildren
     *
     * @return the value of tbl_touristinfo.isChildren
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public String getIschildren() {
        return ischildren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.isChildren
     *
     * @param ischildren the value for tbl_touristinfo.isChildren
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setIschildren(String ischildren) {
        this.ischildren = ischildren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.IDCard
     *
     * @return the value of tbl_touristinfo.IDCard
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.IDCard
     *
     * @param idcard the value for tbl_touristinfo.IDCard
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.tourSeat
     *
     * @return the value of tbl_touristinfo.tourSeat
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public String getTourseat() {
        return tourseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.tourSeat
     *
     * @param tourseat the value for tbl_touristinfo.tourSeat
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setTourseat(String tourseat) {
        this.tourseat = tourseat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.creatby
     *
     * @return the value of tbl_touristinfo.creatby
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public String getCreatby() {
        return creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.creatby
     *
     * @param creatby the value for tbl_touristinfo.creatby
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setCreatby(String creatby) {
        this.creatby = creatby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.createTime
     *
     * @return the value of tbl_touristinfo.createTime
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.createTime
     *
     * @param createtime the value for tbl_touristinfo.createTime
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.updateby
     *
     * @return the value of tbl_touristinfo.updateby
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.updateby
     *
     * @param updateby the value for tbl_touristinfo.updateby
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_touristinfo.updateTime
     *
     * @return the value of tbl_touristinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_touristinfo.updateTime
     *
     * @param updatetime the value for tbl_touristinfo.updateTime
     *
     * @mbggenerated Thu Mar 24 15:33:09 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}