package com.lhzl.drp.model;

import java.util.Date;

public class Traininfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_traininfo.trainId
     *
     * @mbggenerated
     */
    private Long trainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_traininfo.trainNo
     *
     * @mbggenerated
     */
    private String trainno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_traininfo.trainName
     *
     * @mbggenerated
     */
    private String trainname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_traininfo.plateNum
     *
     * @mbggenerated
     */
    private String platenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_traininfo.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_traininfo.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_traininfo.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_traininfo.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_traininfo.trainId
     *
     * @return the value of tbl_traininfo.trainId
     *
     * @mbggenerated
     */
    public Long getTrainid() {
        return trainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_traininfo.trainId
     *
     * @param trainid the value for tbl_traininfo.trainId
     *
     * @mbggenerated
     */
    public void setTrainid(Long trainid) {
        this.trainid = trainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_traininfo.trainNo
     *
     * @return the value of tbl_traininfo.trainNo
     *
     * @mbggenerated
     */
    public String getTrainno() {
        return trainno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_traininfo.trainNo
     *
     * @param trainno the value for tbl_traininfo.trainNo
     *
     * @mbggenerated
     */
    public void setTrainno(String trainno) {
        this.trainno = trainno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_traininfo.trainName
     *
     * @return the value of tbl_traininfo.trainName
     *
     * @mbggenerated
     */
    public String getTrainname() {
        return trainname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_traininfo.trainName
     *
     * @param trainname the value for tbl_traininfo.trainName
     *
     * @mbggenerated
     */
    public void setTrainname(String trainname) {
        this.trainname = trainname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_traininfo.plateNum
     *
     * @return the value of tbl_traininfo.plateNum
     *
     * @mbggenerated
     */
    public String getPlatenum() {
        return platenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_traininfo.plateNum
     *
     * @param platenum the value for tbl_traininfo.plateNum
     *
     * @mbggenerated
     */
    public void setPlatenum(String platenum) {
        this.platenum = platenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_traininfo.createby
     *
     * @return the value of tbl_traininfo.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_traininfo.createby
     *
     * @param createby the value for tbl_traininfo.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_traininfo.createTime
     *
     * @return the value of tbl_traininfo.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_traininfo.createTime
     *
     * @param createtime the value for tbl_traininfo.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_traininfo.updateby
     *
     * @return the value of tbl_traininfo.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_traininfo.updateby
     *
     * @param updateby the value for tbl_traininfo.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_traininfo.updateTime
     *
     * @return the value of tbl_traininfo.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_traininfo.updateTime
     *
     * @param updatetime the value for tbl_traininfo.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}