package com.lhzl.drp.model;

import java.math.BigDecimal;
import java.util.Date;

public class Triprules {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.tripId
     *
     * @mbggenerated
     */
    private Long tripid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.tripType
     *
     * @mbggenerated
     */
    private String triptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.busLocation
     *
     * @mbggenerated
     */
    private String buslocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.starttime
     *
     * @mbggenerated
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.createby
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.updateby
     *
     * @mbggenerated
     */
    private String updateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_triprules.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.tripId
     *
     * @return the value of tbl_triprules.tripId
     *
     * @mbggenerated
     */
    public Long getTripid() {
        return tripid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.tripId
     *
     * @param tripid the value for tbl_triprules.tripId
     *
     * @mbggenerated
     */
    public void setTripid(Long tripid) {
        this.tripid = tripid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.tripType
     *
     * @return the value of tbl_triprules.tripType
     *
     * @mbggenerated
     */
    public String getTriptype() {
        return triptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.tripType
     *
     * @param triptype the value for tbl_triprules.tripType
     *
     * @mbggenerated
     */
    public void setTriptype(String triptype) {
        this.triptype = triptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.busLocation
     *
     * @return the value of tbl_triprules.busLocation
     *
     * @mbggenerated
     */
    public String getBuslocation() {
        return buslocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.busLocation
     *
     * @param buslocation the value for tbl_triprules.busLocation
     *
     * @mbggenerated
     */
    public void setBuslocation(String buslocation) {
        this.buslocation = buslocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.starttime
     *
     * @return the value of tbl_triprules.starttime
     *
     * @mbggenerated
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.starttime
     *
     * @param starttime the value for tbl_triprules.starttime
     *
     * @mbggenerated
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.price
     *
     * @return the value of tbl_triprules.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.price
     *
     * @param price the value for tbl_triprules.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.remark
     *
     * @return the value of tbl_triprules.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.remark
     *
     * @param remark the value for tbl_triprules.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.createby
     *
     * @return the value of tbl_triprules.createby
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.createby
     *
     * @param createby the value for tbl_triprules.createby
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.createTime
     *
     * @return the value of tbl_triprules.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.createTime
     *
     * @param createtime the value for tbl_triprules.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.updateby
     *
     * @return the value of tbl_triprules.updateby
     *
     * @mbggenerated
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.updateby
     *
     * @param updateby the value for tbl_triprules.updateby
     *
     * @mbggenerated
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_triprules.updateTime
     *
     * @return the value of tbl_triprules.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_triprules.updateTime
     *
     * @param updatetime the value for tbl_triprules.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}